# Date:         2014.05.14
# Pupose:       Build a debian based container whith Facebook Scribe installed
# Author:       Michael Klöckner
# Version:      0.1
# Source: 	With the help of Markus Fix "http://deeprecursion.com/"
#


FROM debian:sid
MAINTAINER Michael Klöckner <mkl AT im7 DOT de>




#ADD install.sh /usr/local/bin/install
#RUN /usr/local/bin/install
#ADD run.sh /usr/local/bin/run
#ENTRYPOINT ["/usr/local/bin/run"]

#EXPOSE 9160 7000 7001 9042 7199
